---
- name: Check subscription-manager
  hosts: all

  tasks:
    - name: Run identity
      ansible.builtin.command: subscription-manager identity
      register: results

    - set_fact:
        newvar: '{{ results | regex_replace("\s","") }}'
        
    - name: Show variable
      ansible.builtin.debug:
        #var: results.stdout_lines | to_nice_json
        var: newvar
        
    - name: Show org
      ansible.builtin.debug:
        #var: results.stdout_lines | to_nice_json
        var: newvar.stdout_lines.orgname
