---
- hosts: all
  gather_facts: False
  vars:
     dnf_option: ""

  tasks:
    - name: Update every package on the system
      command: dnf "{{ dnf_option }}"
      when: dnf_option == "update"
      register: my_dnf
      tags: update

    - debug:
        msg: "{{ my_dnf }}"

    - name: Check-updates availables for installed packages and dependencies
      command: dnf "{{ dnf_option }}"
      when: dnf_option == "check-update"
      register: my_dnf
      tags: check-update

    - debug:
        msg: "{{ my_dnf }}"

    - name: List availables all packages and available for RPM-based linux distro
      command: dnf "{{ dnf_option }}"
      when: dnf_option == "list"
      register: my_dnf
      tags: list

    - debug:
        msg: "{{ my_dnf }}"
        
    - name: Print list of all enabled repositories
      command: dnf "{{ dnf_option }}"
      when: dnf_option == "repolist"
      register: my_dnf
      tags: repolist

    - debug:
        msg: "{{ my_dnf }}"
        
    - name: Show information of what has happened in the DNF"s past execution
      command: dnf "{{ dnf_option }}"
      when: dnf_option == "history"
      register: my_dnf
      tags: history

    - debug:
        msg: "{{ my_dnf }}"