---
- name: Upgrading RPM module based on location
  hosts: all
  gather_facts: true
  vars:
    package_name: ''

  tasks:
  #  - name: Look for the file
  #    shell:
  #      cmd: ls -l /tmp/wine*
        
   # - debug: msg="the value of foo.txt is {{lookup('file', '/tmp/wine-mono-7.2.0-1pclos2022.noarch.rpm') }}"
        
    - name: Fetch RPM to install
      fetch:
        src: /tmp/wine-mono-7.2.0-1pclos2022.noarch.rpm
        dest: /home/student1/wine-mono-7.2.0-1pclos2022.noarch.rpm
      delegate_to: ansible-1
