---
- name: Upgrading RPM module based on location
  hosts: all
  gather_facts: true
  become_user: root
  vars:
    package_name: ''

  tasks:
    - name: Copy RPM to install with dnf
      become: true
      copy:
        src: tmp/{{package_name}}
        dest: /tmp/{{package_name}}
        owner: awx
        group: awx
        mode: 0644
        remote_src: false
        
    - name: Look for the file
      shell:
        cmd: ls -l /tmp/wine*

    - name: Install RPM package {{package_name}}
      dnf:  name=/tmp/{{package_name}}
      when: ansible_os_family == "RedHat" and ansible_pkg_mgr == "dnf"
      tags: [packages, work, txt, atom]
      
    #- name: Update RPM
    #  yum:
    #    name: "/var/tmp/{{package_name}}"
    #    state: latest
